### ISSUE TITLE
The system cannot find the path specified:

### ISSUE THREAD

**Issue by Purp-le** [BenjaminHalko/WiiMusicEditorPlus#2]
So, I kind of know the problem, the thing is I don't know how to solve it.

Some time ago I changed my Windows name to something else ("Purple" [no, seriously]), so the program is trying to find a file/folder called "`WiiMusicEditorPlus`" located in "`C:/Users/[user]/AppData/Local/WiiMusicEditorPlus`". But, since my old Windows name was linked to my Microsoft account and when I changed it I unlinked it, it's trying to find the file located in "`C:/Users/Purple/[...]`", even though my user folder itself is still called "`thego`".

I'm pretty sure there's probably almost no fix for this problem that could work for everyone in every situation, so is there a way to change the directory it's looking for when starting up the exe?

**Comment by BenjaminHalko** [comment]
Ok I will see if I can a fix for that.

**Comment by BenjaminHalko** [comment]
If you have python installed on your computer can you try running:
```
import os
print(os.path.expanduser('~'))
```
Tell me if that gives the correct name/path of your user folder.

**Comment by BenjaminHalko** [comment]
Try also using [this version](https://github.com/BenjaminHalko/WiiMusicEditorPlus/releases/download/1.0.0-beta.a/WiiMusicEditorPlus-Windows.zip)

**Comment by BenjaminHalko** [comment]
@TheGoldenPotion Any update on this?
